import { BaseRequest, Confirmation, ConfirmationOptionsDetail, ContentType, Context, UserContext, NetworkContext, TransactionalRequest, SampleTutorialRequest, SimpleTest, BaseResponse, SimpleTestResult, SurfaceBaseResponse, CredentialResponse, DashBoardLogResponse, SurfaceBaseRequest, CredentialRequest, DashBoardLogRequest, ImsCredentialRequest } from './../../../autogeneratedindex';



import { Post, PostGeneric, Get } from 'surface-helper/src/helpers/rest-call';


export class CredentialController {
	async ControlUserAuthority(credentialRequest: CredentialRequest, apiUrl: string): Promise<CredentialResponse> {
		let result = {} as CredentialResponse;

		await PostGeneric<CredentialResponse>(apiUrl, '/api/Credential/ControlUserAuthority', credentialRequest)
			.then(
				(response: CredentialResponse) => {
					result = response;
				});

		return result;
	};

	async ControlUserStatus(credentialRequest: CredentialRequest, apiUrl: string): Promise<CredentialResponse> {
		let result = {} as CredentialResponse;

		await PostGeneric<CredentialResponse>(apiUrl, '/api/Credential/ControlUserStatus', credentialRequest)
			.then(
				(response: CredentialResponse) => {
					result = response;
				});

		return result;
	};

	async GetCredentials(credentialRequest: CredentialRequest, apiUrl: string): Promise<CredentialResponse> {
		let result = {} as CredentialResponse;

		await PostGeneric<CredentialResponse>(apiUrl, '/api/Credential/GetCredentials', credentialRequest)
			.then(
				(response: CredentialResponse) => {
					result = response;
				});

		return result;
	};

}



